site_name: AWS Observability Accelerator for Terraform
docs_dir: "docs"
copyright: "Copyright &copy; Amazon 2022"
site_author: "AWS"
site_url: "https://aws-observability.github.io/terraform-aws-observability-accelerator/"
repo_name: "aws-observability/terraform-aws-observability-accelerator"
repo_url: "https://github.com/aws-observability/terraform-aws-observability-accelerator"

theme:
  logo: images/aws-logo.png
  favicon: images/aws-favicon.png
  name: material
  font:
    text: ember
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs.sticky

  palette:
    primary: indigo
    accent: grey

nav:
  - Home: index.md
  - Concepts: concepts.md
  - Amazon EKS:
      - Infrastructure monitoring: eks/index.md
      - EKS API server monitoring: eks/eks-apiserver.md
      - Multicluster monitoring: eks/multicluster.md
      - Java/JMX: eks/java.md
      - Nginx: eks/nginx.md
      - Istio: eks/istio.md
      - Viewing logs: eks/logs.md
      - Tracing: eks/tracing.md
      - Teardown: eks/destroy.md
  - AWS Distro for OpenTelemetry (ADOT):
      - Monitoring ADOT collector health: adothealth/index.md
  - Amazon CloudWatch Container Insights:
      - Amazon EKS: container-insights/eks.md
  - Monitoring Managed Service for Prometheus Workspaces: workloads/managed-prometheus.md
  - Supporting Examples:
      - EKS Cluster with VPC: helpers/new-eks-cluster.md
      - Amazon Managed Grafana setup: helpers/managed-grafana.md
  - Support & Feedback: support.md
  - Contributors: contributors.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - pymdownx.critic
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
